### ISSUE TITLE
build ui version of web app

### ISSUE THREAD

**Issue by henrylin03** [henrylin03/tasks#4]
build user interface (UI) in DOM for to-do list

# checklist
#### tasks
- [x] as a user, when i first load the app, i can see my inbox, which includes tasks not categorised into projects
- [x] as a user, i can see all tasks and their relevant attributes, previewed for me
- [x] #11
- [x] as a user, i can see urgent items made visually distinct
- [x] #16
- [x] #17
- [x] #15
- [x] #26
- [x] when i add a task, i can populate all of the fields, including tagging it to an existing project
- [x] #19
- [x] #27
#### projects
- [x] as a user, i can add a new project
- [x] #9
- [x] as a user, i can see all the projects i have added on the left navbar
- [x] #8
- [x] #29
- [x] #30
- [x] #28
- [x] #31
- [x] #39
- [x] #38

#### misc
- [x] #47
- [x] add favicon
- [ ] #45
- [ ] #46

### lower-priority (but potentially still mvp if we got time)

- [ ] #49
- [ ] #50
- [ ] #51
- [ ] #52
- [ ] #54
- [ ] #53
- [ ] #55
- [ ] #56
- [ ] #57
- [ ] #58
- [ ] #59
- [ ] #60
- [ ] #61

## do later
- [ ] #62
- [ ] #63
- [ ] #64
- [ ] #65
- [ ] #66
- [ ] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [ ] #71
- [ ] #72
- [ ] #73
- [ ] #75
- [ ] #74
- [ ] #76
- [ ] #77
- [ ] #78
- [ ] #79
- [ ] #80
- [ ] #81
- [ ] #82
- [ ] #83
- [ ] #84
- [ ] #85
- [ ] #86
- [ ] #92
- [ ] #93
- [ ] #91
- [ ] #90
- [ ] #89
- [ ] #87
- [ ] #88

**Comment by henrylin03** [comment]
reprioritised tasks as this is taking too long

**Comment by henrylin03** [comment]
reprioritised tasks

**Comment by henrylin03** [comment]
reopening to capture further todos
